openapi: 3.0.0
info:
  title: Log File API
  description: API to read log files with optional pagination and gzip compression.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /logs:
    post:
      summary: Retrieve log file content
      requestBody:
        description: JSON object containing the filename and optional parameters for lines, page, and page_size.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: The name of the log file to read.
                lines:
                  type: integer
                  description: The number of lines to read from the end of the log file.
                  example: 100
                page:
                  type: integer
                  description: The page number to retrieve.
                  example: 1
                page_size:
                  type: integer
                  description: The number of lines per page.
                  example: 500
              required:
                - filename
      responses:
        '200':
          description: Log file content
          content:
            text/plain:
              schema:
                type: string
          headers:
            Content-Encoding:
              schema:
                type: string
                enum: [gzip]
        '400':
          description: Invalid request parameters
        '404':
          description: Log file not found
